import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { AuthContextProvider } from "@/Context/AuthContext";

const dm = DM_Sans({ weight: "300", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={dm.className}>
        <AuthContextProvider>
          <div className="flex tracking-wider gap-4 bg-bg flex-col">
            <Navbar></Navbar>
            {children}
          </div>
        </AuthContextProvider>
      </body>
    </html>
  );
}
